/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was created using the `create_project.py` script located in the
 * `<AndroidX root>/development/project-creator` directory.
 *
 * Please use that script when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import androidx.build.PlatformIdentifier
import androidx.build.SoftwareType
import org.gradle.api.GradleException
import org.gradle.api.tasks.Copy
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.konan.target.KonanTarget

plugins {
    id("AndroidXPlugin")
    id("AndroidXComposePlugin")
    id("JetBrainsAndroidXPlugin")
    id("androidx.inspection")
}

androidXMultiplatform {
    def androidTarget = androidLibrary {
        compileSdk = 35
        // layout inspection supported starting on Android Q
        minSdk = 29
        namespace = "androidx.compose.ui.inspection"
    }
    jvm()

    defaultPlatform(PlatformIdentifier.ANDROID)

    def prepareJvmtiHeader = tasks.register("prepareJvmtiHeader", Copy) {
        def jvmtiHeader = providers.provider {
            def javaHome = System.getenv("JAVA_HOME") ?: System.getProperty("java.home")
            def header = new File(javaHome, "include/jvmti.h")
            if (!header.exists()) {
                throw new GradleException("Cannot find jvmti.h at ${header}")
            }
            header
        }
        from(jvmtiHeader)
        into(layout.buildDirectory.dir("generated/jvmti"))
    }

    def composeInspectionJni = createNativeCompilation("compose_inspection_jni") {
        configureEachTarget { nativeCompilation ->
            nativeCompilation.sources.from(
                    fileTree("src/androidMain/cpp").matching { include "**/*.cpp" }
            )
            nativeCompilation.includes.from(
                    prepareJvmtiHeader.map { it.destinationDir }
            )
            nativeCompilation.freeArgs.addAll("-Wall", "-Werror")
            nativeCompilation.linkerArgs.addAll(
                    "-landroid",
                    "-llog",
                    "-Wl,-z,max-page-size=16384"
            )
        }
        configureTargets([
                KonanTarget.ANDROID_ARM32.INSTANCE,
                KonanTarget.ANDROID_ARM64.INSTANCE,
                KonanTarget.ANDROID_X64.INSTANCE,
                KonanTarget.ANDROID_X86.INSTANCE,
        ])
    }

    if (androidTarget != null) {
        addNativeLibrariesToJniLibs(androidTarget, composeInspectionJni)
    }

    sourceSets {
        commonMain {
            dependencies {
                compileOnly(project(":collection:collection"))
                compileOnly(project(":compose:runtime:runtime"))
                compileOnly(project(":compose:ui:ui"))
            }
        }

        commonTest {
            dependencies {
                implementation(libs.kotlinTest)
            }
        }

        jvmAndAndroidMain {
            dependencies {
                implementation(libs.kotlinReflect)
                implementation(libs.protobufLite)
                implementation(project(":compose:ui:ui-inspection-proto"))
            }
        }

        jvmMain {
            dependencies {
                implementation(libs.skikoCurrentOs)
                implementation(project(":compose:foundation:foundation"))
            }
        }

        androidMain {
            dependencies {
                implementation("androidx.annotation:annotation:1.8.1") {
                    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib"
                }
                // Following dependencies will be provided by inspected app itself
                // because compose:ui-inspector can be run only in app with compose:ui:ui
                // thus all its transitive dependencies will be present too.
                compileOnly(libs.kotlinCoroutinesAndroid)
                compileOnly("androidx.collection:collection:1.4.2")
                compileOnly(androidx.projectOrArtifact(":inspection:inspection"))
                compileOnly(project(":compose:runtime:runtime"))
                compileOnly(project(":compose:ui:ui-graphics"))
                compileOnly(project(":compose:ui:ui"))
                // we ignore its transitive dependencies, because ui-inspection should
                // depend on them as "compile-only" deps.
                implementation(project(":compose:ui:ui-tooling-data")) {
                    transitive = false
                }
            }
            kotlin.srcDirs += "src/androidMain/java"
            resources.srcDirs += "src/androidMain/resources"
        }

        androidDeviceTest {
            dependencies {
                implementation(libs.kotlinCoroutinesAndroid)
                implementation(libs.testCore)
                implementation(project(":compose:foundation:foundation-layout"))
                implementation(project(":compose:ui:ui-tooling"))
                implementation(project(":compose:ui:ui-tooling-data"))
                implementation(project(":compose:ui:ui"))
                implementation(project(":compose:foundation:foundation"))
                implementation(project(":compose:ui:ui-util"))
                implementation(project(":compose:ui:ui-test-junit4"))
                implementation(project(":internal-testutils-fonts"))
                implementation(project(":compose:material:material"))
                implementation("androidx.compose.material:material-icons-core:1.6.7")
                implementation("androidx.compose.material3:material3-android:1.3.1")
                def inspectionTesting = project.findProject(":inspection:inspection-testing")
                if (inspectionTesting != null) {
                    implementation(inspectionTesting)
                }
                implementation("androidx.activity:activity-compose:1.3.1")
                implementation(libs.testRunner)
                implementation(libs.testRules)
                implementation(libs.testExtJunit)
                implementation(libs.espressoCore)
                implementation(libs.truth)
            }
            kotlin.srcDirs += "src/androidDeviceTest/java"
            resources.srcDirs += "src/androidDeviceTest/res"
        }
    }
}

inspection {
    name = "compose-ui-inspection.jar"
    allowedModules.addAll(
            "org.jetbrains.kotlin:kotlin-reflect"
    )
}

androidx {
    name = "Compose Layout Inspector"
    type = SoftwareType.IDE_PLUGIN
    inceptionYear = "2021"
    description = "Compose layout inspector. Exposes information to our tools for better IDE support."
}

// TODO(b/407640608): Fix :compose:ui:ui-inspection:connectedCheck to work without this block
tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-Xlambdas=class"
        ]
    }
}